//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viewTry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViewTryDBEntities : DbContext
    {
        public ViewTryDBEntities()
            : base("name=ViewTryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SiteUser> SiteUsers { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public object SiteUser { get; internal set; }
    }
}
